[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.110.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.110.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.110.0"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.110.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.jpg" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "https://smpmuhima.sch.id/job"
  to = "https://smpmuhima.sch.id/form/job-vacancy/"
  status = 301
  force = true

[[redirects]]
  from = "https://smpmuhima.sch.id/ppdb"
  to = "https://smpmuhima.sch.id/form/registration-new-students/"
  status = 301
  force = true

[[redirects]]
  from = "https://smpmuhima.sch.id/daftar"
  to = "https://smpmuhima.sch.id/form/registration-new-students/"
  status = 301
  force = true
